yalla_notlob/config/routes.rb
Rails.application.routes.draw do

  resources :order_details
  resources :notifications
  resources :orders do
    resources :items
  end
  get 'follows/index'

  get 'home/index'
  get 'all' => 'users#all'
  get '/complete/:id', to: 'orders#complete'
  get '/join/:id', to: 'order_details#join'
  # match 'add', to: 'order_details#add', via: [:post]
  # post 'invite' => 'users#invite'
  # match 'invites', to: 'users#invite', via: [:post]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
     resources :groups
  end
  resources :groups

  resources :groups do
    member do
      post :new_member
      delete :delete_member
     # post '/newfollow', to: 'users#newfollow'
    end
 end

  resources :follows
 match 'users/newfollow' => 'users#newfollow', :via => :post
  resources :users do
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end
 #root 'users#index'
 root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla_notlob/app/models/group.rb
class Group < ApplicationRecord
  acts_as_followable
  belongs_to :user
  has_many :user_groups
  has_many :orders
  has_many :users, through: :user_groups
end

yalla_notlob/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json#web_serves

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @group = current_user.groups.build
    @usergroup=UserGroup.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
     @groups = Group.all
     @groupm = current_user.groups.build
    @usergroup=UserGroup.all
    @users=User.all

  end


  def show_users
    #todo make it for for the group only

    @usersIds= UserGroup.where(group_id: params[:id]).map { |e| e.user_id }
    respond_with User.where(id: @usersIds)

  end

  # GET /groups/new
  def new_member
    @email = params[:user][:email]
    @group = Group.find(params[:id])
    if @email !=""
     @user = User.find_by_email(@email)
      if @user != nil
       if current_user != @user.id
         if current_user.following?(@user)
            @userfound = UserGroup.where(:user_id => @user.id , :group_id => @group.id )
            if @userfound.exists? == false
                @usergroup = UserGroup.new(
                group_id: @group.id,
                user_id: @user.id )
                @usergroup.save


                redirect_to  group_path(@group.id)
            else
            
            flash[:notice] = 'Oopps! Frined aready exist!!'
              

                  redirect_to  group_path(@group.id)
            end
         else
             
	     flash[:notice] = 'Oopps! a user not a friend '
             flash[:notice] = 'Oopps! You Can Not Add YouSelf To Group!!'	
            redirect_to  group_path(@group.id)
         end
       else
            
            flash[:notice] = 'Oopps! You Can Not Add YouSelf To Group!!'
          redirect_to  group_path(@group.id)
       end
     else
             
             flash[:notice] = 'Oopps! Not A User!'
      redirect_to  group_path(@group.id)
     end
   else
        
        flash[:notice] = 'Oopps! Inser An Email !'
    redirect_to group_path(@group.id)
 end

end

  # GET /groups/1/edit
  def delete_member
    @usergroup = UserGroup.find(params[:id])
    @usergroup.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group member was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  # POST /groups
  # POST /groups.json
  def create
    if params[:group][:name] !=""
      @group = current_user.groups.build(group_params)
      @group.user_id = current_user.id

      respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
    else
      respond_to do |format|
        format.html { redirect_to groups_url, notice: 'Group creation failed.' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.where(id: params[:id]).take

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

yalla_notlob/app/helpers/groups_helper.rb
module GroupsHelper
end

yalla_notlob/app/views/groups/_form.html.erb
<%= form_for([@user,@group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

yalla_notlob/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

yalla_notlob/app/views/groups/index.html.erb
<h1></h1>
<div class="container">
 <div class="page-header">
 <h1>Groups</h1>
</div>
</div>
<div class="container">
 <div class="row">
   <div class="col-md-6 col-md-offset-3">
     <div id="group-form" >
       <%= form_for(@group) do |f| %>
         <% if @group.errors.any? %>
           <div id="error_explanation">
             <ul>
             </ul>
           </div>
         <% end %>
         <div class="form-group">
           <h4><%= f.label :'Group'%></h4>
           <%= f.text_field :name, class: "form-control", placeholder: "Enter Group Name" %>
         </div>
         <%= f.submit "Add", class: 'btn btn-primary' %>
       <% end %>
     </div>
   </div>
 </div>
</div>
<br/>
<div class="container">
 <div class="row">
   <div class="col-md-4">
     <div class="panel panel-default">
       <div class="panel-body">
         <table class="table">
<caption><h2>My Groups</h2></caption>
  <tbody>
    <% @groups.each do |group| %>
             <% if group.user_id == current_user.id %>
             <tr>
               <td><%= group.name %></td>
               <td>
                 <%= link_to "Display", group,:class => "btn btn-warning", :method => :get %>
               </td>
               <td>
                 <%= link_to "Delete", group,:class => "btn btn-danger", :method => :delete , data: { confirm: 'Are you sure?' } %>
               </td>
             </tr>
             <% end %>
    <%end%>
  </tbody>
</table>
       </div>
     </div>
   </div>
   <div class="col-md-8">

     </div>
 </div>
</div>
</div>

yalla_notlob/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', user_groups_path %>

yalla_notlob/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="page-header">
  <h1>Groups</h1>
</div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div id="group-form" >
            <%= form_for Group.new do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <ul>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
    <h4><%= f.label :'Group' %></h4>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Group Name" %>
  </div>
     <%= f.submit "Add", class: 'btn btn-primary' %>
  <% end %>
  </div>
    </div>
</div>
<br/>
<div class="container">
  <div class="row">
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <table class="table">
              <caption><h2>My Groups</h2></caption>
              <tbody>
                <% @groups.each do |group| %>
                  <% if group.user_id == current_user.id %>
                    <tr>
                      <td><%= group.name %></td>
                      <td>
                        <%= link_to "Display", group,:class => "btn btn-warning", :method => :get %>
                      </td>
                      <td>
                        <%= link_to "Delete", group,:class => "btn btn-danger", :method => :delete , data: { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-9 col-md-offset-2">
                <div class="row">
                  <div id="group-form" >
                    <%= form_for User.new, url: new_member_group_path(@group.id) do |f| %>
                      <div class="col-md-8">
                        <div class="form-group">
                          <%= f.text_field :email, class: "form-control", placeholder: "Enter email here" %>
                        </div>
                      </div>
                      <div class="col-md-3">
                          <%= f.submit "Add", class: 'btn btn-primary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="container">
              <h2>Friends Member</h2>
              <br/>
              <div class="row">
                <% @usergroup.each do |user| %>
                  <% if user.group_id == @group.id %>
                    <% @users.each do |username| %>
                    <% if current_user.following?(username) %>
                      <% if username.id == user.user_id %>
                        <div class="col-md-2">
                          <div class="container">
                            <h4><%= username.name %></h4>
                            <span id="follow_user<%=user.id%>">
                            <%= link_to(delete_member_group_path(user.id), class:'btn btn-danger', :method => :delete , data: { confirm: 'Are you sure?' }) do %>
                              <i class="icon-remove icon-white"></i>
                              Delete
                            <% end %></span><p></p>
                          </div>
                        </div>
                      <% end %>
                      <%end %>
                    <%end %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <br/>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>