yalla_notlob/config/routes.rb
Rails.application.routes.draw do

  resources :order_details
  resources :notifications
  resources :orders do
    resources :items
  end
  get 'follows/index'

  get 'home/index'
  get 'all' => 'users#all'
  get '/complete/:id', to: 'orders#complete'
  get '/join/:id', to: 'order_details#join'
  # match 'add', to: 'order_details#add', via: [:post]
  # post 'invite' => 'users#invite'
  # match 'invites', to: 'users#invite', via: [:post]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
     resources :groups
  end
  resources :groups

  resources :groups do
    member do
      post :new_member
      delete :delete_member
     # post '/newfollow', to: 'users#newfollow'
    end
 end

  resources :follows
 match 'users/newfollow' => 'users#newfollow', :via => :post
  resources :users do
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end
 #root 'users#index'
 root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla_notlob/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_attached_file :order_image,
                      :default_url => "/app/assets/images/missing.png",
                      styles: { thumb: ["64x64#", :jpg],
                      original: ['500x500>', :jpg] },
                      convert_options: { thumb: "-quality 75 -strip",
                                     original: "-quality 85 -strip" },
                  hash_secret: "abc123",
                  preserve_files: "true"
  validates_attachment :order_image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

yalla_notlob/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order=Order.find(params[:id])
    @items = @order.items.all
    @item=@order.items.new
    @order_details = @order.order_details.all
    @friends_Invited=[]
    @friends_Joined=[]
    @order_details.each do |i|
      @user=User.find(i.user_id)
      @friends_Invited.push(@user.name)
      if i.joined == true
        @user=User.find(i.user_id)
        @friends_Joined.push(@user.name)
      end
    end
    render template: 'items/index'
  end

  # GET /orders/new
  def new
    @order = Order.new
    @notifications=Notification.all
    @notification=Notification.new
  end

  # GET /orders/1/edit
  def edit
  end
  def complete
    @order=Order.find(params[:id])
    @order.status = "Finished"
   @order.save
  end
  # POST /orders
  # POST /orders.json
  def create
    puts "test000"
    invited= params[:friends_invited]

    puts params.inspect
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.invited = invited.length
    @order.joined = 0
    @order.status = "waiting"
    respond_to do |format|
      if @order.save

        invited.each do |i|
          @group_invited = Group.where(name: i)
          @user_invited = User.where(name: i)
          if(@group_invited.present?)
            puts "test-group"
            @group_id = @group_invited.ids
            puts @group_id
            @members = UserGroup.where(group_id: @group_id).all
            puts @members.inspect
            @members.each do |m|
              @group_invite = OrderDetail.new
              @group_invite.user_id = m.user_id
              @group_invite.order_id = @order.id
              @group_invite.joined = 0
              puts @group_invite.inspect
              if @group_invite.save
                puts "Group Invited"
              end
            end
          else
            puts "test-user"
            user_invs = OrderDetail.new
            puts @user_invited.ids.class
            user_invs.user_id = @user_invited.ids[0]
            user_invs.order_id = @order.id
            puts user_invs.user_id
            user_invs.joined = 0
            puts user_invs.inspect
            if user_invs.save
              puts "User Invited"
            end
          end
        end
        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }

        ##################################### test pusher####################################
        Pusher.trigger('my-channel', 'my-event', {
            message: current_user.name.to_s<<" invited  "<<invited.join(",")<<" to "<<@order.meal,
            id: @order.id
        })
        ##################################### test pusher####################################
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
      @order.user_id = current_user.id
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:meal, :user_id, :group_id, :restaurant, :joined, :invited, :status, :image, :order_image)
    end
end

yalla_notlob/app/helpers/orders_helper.rb
module OrdersHelper
end

yalla_notlob/app/views/orders/_form.html.erb
<script>

$( function() {
  var availableTags =[];
  var people_invited =[];
  $.ajax({
    url:"/all",
    method:"GET",
    success:function(data){
      names=JSON.parse(data)
      for(i=0;i<names.length;i++){
        availableTags[i]=names[i]
      }
      console.log("users:"+ availableTags);
    }
  })
  $( "#friends" ).autocomplete({
    source: availableTags
  });
   $( "#friends" ).on( "blur", function( event, ui ) {

       people_invited.push($(this).val())
//       $.ajax({
//           url:"/add",
//           method:"POST",
//           data:{data:$(this).val()},
//           success:function(data){
//               names=JSON.parse(data)
//              console.log(names);
//           }
//       })
     $("#invitedFriends").append("<div class='col-md-2' style='border:1px solid black; margin:5px;max-height:50px;'><h4 class='friend_invited'>"+$(this).val()+"</h4></div>")
    $("#friends_invited").append("<input type='checkbox' name='friends_invited[]' value="+$(this).val()+" checked>"+$(this).val()+"")
     // dispatcher.trigger 'invite.new',true
   } );

//  $("form").on("submit", function (e) {
////      $.ajax({
////          url:"/invites",
////          method:"POST",
////          data:{invited:JSON.stringify(people_invited)},
////          dataType: "json",
////          success:function(data){
////              invites=JSON.parse(data)
////              console.log("invited users :"+ invites);
////          },
////          error:function (error) {
////              console.log("error")
////          }
////      })
//      e.preventDefault();
//
////      people_invited=people_invited.serializeArray()
//      console.log(JSON.stringify(people_invited))
//      data=$(this).serialize()
//      data+=JSON.stringify(people_invited)
//      console.log(data)
//      $.post($(this).attr("action"),data)
//
//  })
} );

</script>
<%= form_for @order, html: { multipart: true } do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="border-form-div">
  <div class="field">
    <%= f.label :meal %>
    <%= f.text_field :meal %>
  </div>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :group_id %>
    <%= f.collection_select(:group_id, Group.all, :id, :name ) %>

  </div>

  <div class="field">
    <%= f.label :restaurant %>
    <%= f.text_field :restaurant %>
  </div>

  <div class="field ui-widget">
    <label for="friends">Friends</label>
    <input type="text" name="friends" id="friends" value=""> <span>Invited when Blur</span>
  </div>

    <div class="field" id="friends_invited">
      <label for="friends_invited">Friends_Invited</label>

    </div>

  <div class="field">
    <%= f.label :order_image %>
       <%= f.file_field :order_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>
<!-- <form class="" action="" method="post">
  <input type="text" id="message" name="body" value="">
  <input type="submit" id="new_invite" name="submit" value="Invite">
</form> -->

yalla_notlob/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order, :class => 'btn btn-sm btn-success' %> |
<%= link_to 'Back', orders_path, :class => 'btn btn-sm btn-success' %>

yalla_notlob/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>
<%= link_to 'New Order', new_order_path,id: "newOrder",class: 'pull-right',:class=>'btn btn-sm btn-success' %>

<table ducts</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Meal</th>
      <th>User</th>
      <th>Group</th>
      <th>Restaurant</th>
      <th>Joined</th>
      <th>Invited</th>
      <th>Status</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.meal %></td>
        <td><%= order.user.name %></td>
        <td><%= order.group.name %></td>
        <td><%= order.restaurant %></td>
        <td><%= order.joined %></td> <!-- must be reviewed  -->
        <td><%= order.invited %></td>
        <td>
          <%= order.status %>
          <% if order.user_id == current_user.id && order.status != "Finished" %>
              <span><input class="complete btn btn-xs btn-primary" name="<%= order.id %>" value="Completed" type="submit"></span>
          <% end %>
        </td>
        <td><div class="media">
          <div class="media-left">
          <%= link_to image_tag(order.order_image.url(:thumb), class: 'media-object'), order.order_image.url, target: '_blank' %>          </div>
           <%= link_to 'Remove', order_path(order), class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
        <td><%= link_to 'Show', order, :class => 'btn btn-sm btn-success' %></td>
        <td><%= link_to 'Edit', edit_order_path(order), :class => 'btn btn-sm btn-warning' %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<script>
$(function (e) {
    $(".complete").on("click", function (e) {
        e.preventDefault()
        data=$(this).attr("name")
        console.log("order id ="+data)
        $.ajax({
            url: "/complete/" + data,
            method: "GET",
            success:function (success) {
                console.log("success")
            },
            error:function (error) {
                console.log("error")
            }

        })
    })
})
</script>

yalla_notlob/app/views/orders/new.html.erb
  <h2>Notifications</h2>
<div id="messages">
  <!-- <select id="nots" class="dropdown alert pull-right" >

    <% @notifications.each do |n| %>
      <option><%= n.message %></option>
    <% end %>
  </select> -->
 <%= render partial: 'notifications/notification', collection: @notifications %>
</div>
<script type="text/javascript">
  $(function() {
    $('#nots option').last().prop('selected',true);
  })
</script>
<h1>New Order</h1>
<div style="float:left;max-width:30%;">
  <%= render 'form', order: @order %>

</div>

<div id="invitedFriends" style="text-align:center;float:right;width:500px;height:350px;border:1px groove black;">
  <h3>Friends or Groups Invited</h3>

</div>
<div style="clear:both;">
  <%= link_to 'Back', orders_path, :class => 'btn btn-sm btn-success' %>
</div>