yalla_notlob/config/routes.rb
Rails.application.routes.draw do

  resources :order_details
  resources :notifications
  resources :orders do
    resources :items
  end
  get 'follows/index'

  get 'home/index'
  get 'all' => 'users#all'
  get '/complete/:id', to: 'orders#complete'
  get '/join/:id', to: 'order_details#join'
  # match 'add', to: 'order_details#add', via: [:post]
  # post 'invite' => 'users#invite'
  # match 'invites', to: 'users#invite', via: [:post]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
     resources :groups
  end
  resources :groups

  resources :groups do
    member do
      post :new_member
      delete :delete_member
     # post '/newfollow', to: 'users#newfollow'
    end
 end

  resources :follows
 match 'users/newfollow' => 'users#newfollow', :via => :post
  resources :users do
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end
 #root 'users#index'
 root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla_notlob/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'YallaNotlob',  user_session , class: 'navbar-brand' %>
    </div>
<% if user_signed_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home',   home_index_path  %><span class="sr-only">(current)</span></li>
        <li><%= link_to 'Freinds',  users_path %></li>
        <li><%= link_to 'Group',  groups_path %></li>
         <li><%= link_to 'Order', orders_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- #notification is here -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Notifications <span class="fa fa-bell"><span class="label label-warning " id="notifyNum"></span></span><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" id="notify_list">

          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
            <!-- <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li> -->
    <% else %>
         <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      </ul>

    <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <%= javascript_include_tag "entangled-js.js" %>
  </div><!-- /.container-fluid -->
</nav>

yalla_notlob/app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

yalla_notlob/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaNotlob</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>
    <%= render '/layouts/nav' %>
  <!-- <% if user_signed_in? %>
  <%= link_to 'logout' ,destroy_user_session_path , method: :delete%>
 <%end %> -->
 <div class="container">
   <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>">
       <%= value %>
     </div>
   <% end %>
 </div>

 <div class="container"><%= yield :top_content %>
 </div>

 <div class="container">
     <h1><%= yield :header %></h1>
   <%= yield %>
 </div>

 <div class="push"></div>

 </div>
  <!---------------------------------------- Test Pusher----------------------------------------------------------------->
  <!--<script src="https://js.pusher.com/4.0/pusher.min.js"></script>-->
  <!--<script>-->
<!--
//      // Enable pusher logging - don't include this in production
//      Pusher.logToConsole = true;
//
//      var pusher = new Pusher('fe81d712cb3fb9c96918', {
//          cluster: 'eu',
//          encrypted: true
//      });
//
//      var channel = pusher.subscribe('my-channel');
//      channel.bind('my-event', function(data) {
//          alert(data.message);
//        var list=document.getElementById("notify_list");
////         Don't forget add here link like in production
//
<!--////            <input id='join' value='Join' type='submit' name='' class='joined btn btn-success ' >-->
       <!--});-->
  <!--</script>-->

  <!--############################################# Production ##########################################################-->
  <script src="https://js.pusher.com/4.0/pusher.min.js"></script>
  <script>

      // Enable pusher logging - don't include this in production
//      Pusher.logToConsole = true;

      var pusher = new Pusher('1db7b63c27bdfa0130d9', {
          cluster: 'eu',
          encrypted: true
      });
//    Depeloment
//      var pusher = new Pusher('fe81d712cb3fb9c96918', {
//          cluster: 'eu',
//          encrypted: true
//      });

      var channel = pusher.subscribe('my-channel');
      channel.bind('my-event', function(data) {
          alert(data.message+"  Check Notifications");
        var list=document.getElementById("notify_list");
        var notifyNum=document.getElementById("notifyNum");
          notifyNum.innerText= list.childNodes.length;
            list.innerHTML+="<li class='list-item'><a href='<%= @host %>/orders/"+data.id+"'>"+data.message+"</a></li>";
    });

  </script>
  <!---------------------------------------- Test Pusher ---------------------------------------------------------------->

  <!------------------------------------------------------Items Pusher ------------------------------------------------->
  <script>

      var channelItems = pusher.subscribe('items-channel');
      channelItems.bind('last-items', function(data) {
//          alert('Received my-event with message: ' + data.message.name);
          var newItem=document.getElementById("bodyItemsTable");
          var newRow=document.createElement("tr");

          var td1=document.createElement("td");
          td1.innerText=data.message.name;
          newRow.appendChild(td1);

          var td2=document.createElement("td");
          td2.innerText=data.username;
          newRow.appendChild(td2);

          var td3=document.createElement("td");
          td3.innerText=data.ordermeal;
          newRow.appendChild(td3);

          var td4=document.createElement("td");
          td4.innerText=data.message.amount;
          newRow.appendChild(td4);

          var td5=document.createElement("td");
          td5.innerText=data.message.price;
          newRow.appendChild(td5);

          var td6=document.createElement("td");
          td6.innerText=data.message.comment;
          newRow.appendChild(td6);

          newItem.appendChild(newRow);


      });
  </script>
  <!------------------------------------------------------End[Items Pusher] -------------------------------------------->
  <!--<script>-->
  <!--
//  $(function (e) {
//      $(".joined").on("click",function (e) {
//          e.preventDefault()
//          data=$(this).attr("name")
//          console.log("joined id ="+data)
//          $.ajax({
//              url: "/join/" + data,
//              method: "GET",
//              success:function (success) {
//                  console.log("success")
//              },
//              error:function (error) {
//                  console.log("error")
//              }
//
//          })
//      })
//  })
-->
  <!--</script>-->
 </body>
 </html>