yalla_notlob/config/routes.rb
Rails.application.routes.draw do

  resources :order_details
  resources :notifications
  resources :orders do
    resources :items
  end
  get 'follows/index'

  get 'home/index'
  get 'all' => 'users#all'
  get '/complete/:id', to: 'orders#complete'
  get '/join/:id', to: 'order_details#join'
  # match 'add', to: 'order_details#add', via: [:post]
  # post 'invite' => 'users#invite'
  # match 'invites', to: 'users#invite', via: [:post]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
     resources :groups
  end
  resources :groups

  resources :groups do
    member do
      post :new_member
      delete :delete_member
     # post '/newfollow', to: 'users#newfollow'
    end
 end

  resources :follows
 match 'users/newfollow' => 'users#newfollow', :via => :post
  resources :users do
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end
 #root 'users#index'
 root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

yalla_notlob/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
 #devise :omniauthable, :omniauth_providers => [:facebook]
 acts_as_followable
 acts_as_follower
  has_many :groups, dependent: :destroy#method return arr of obj
  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :order_details, dependent: :destroy


# def name
#   email.split('@')[0]
# end



end

yalla_notlob/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  # protect_from_forgery
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  def all
    @users = User.all
    @groups = Group.all
    names=[]
    @users.each do |i|
      names.append(i.name)
    end
    @groups.each do |i|
      names.append(i.name)
    end
    render text: names.inspect
  end

  # def invite
  #    @test = "test"
  #
  #   # invited = params[:invited]
  #    render text: @test
  #   #  respond_to do |format|
  #   #    format.html # index.html.erb
  #   #    format.json { render json: @test }
  #   #  end
  # end

  def newfollow
    @email = params[:user][:email]
    puts "***********************" + @email.inspect + "*****************************"
    # Rails.logg

    if @email!=""

    # puts "***********************" + @email + "*****************************"
     @user = User.find_by_email(@email)
     if @user!= nil
      current_user.follow(@user)
      redirect_to users_path
    else
        redirect_to users_path
   end
   else
     redirect_to users_path {"error "}
    end


  end


  def follow
    unless current_user.id == params[:id]
    @user = User.find(params[:id])
    current_user.follow(@user)
    respond_to do |format|
      format.js {render :action=>"follow"}
    end
   end

  end


  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    respond_to do |format|
      format.js {render :action=>"unfollow"}
  end

 end

end

yalla_notlob/app/helpers/users_helper.rb
module UsersHelper
end

yalla_notlob/app/views/users/_follow_user.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to(unfollow_user_path(user), :remote => true, :class => 'btn btn-danger') do %>
   <i class="icon-remove icon-white"></i>
   UnFriend
 <% end %><p></p>
  <% else %>
    <%= link_to(follow_user_path(user) ,:remote => true, :class => 'btn btn-success') do %>
    <i class="icon-ok icon-white"></i>
    Friend
    <%end%><p></p>
  <% end %>
<% end %>

yalla_notlob/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nom, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :prenom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :prenom, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

yalla_notlob/app/views/users/_user.html.erb
<% if @users.present? %>
  <%= render @users %>
<% else %>
  <p>There are no user containing the term(s) <%= params[:search] %>.</p>
<% end %>

yalla_notlob/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

yalla_notlob/app/views/users/follow.js.erb
$('#follow_user<%=@user.id%>').html('<%= escape_javascript(render :partial => "users/follow_user", :locals => {:user => @user}) %>');

yalla_notlob/app/views/users/index.html.erb
<%- model_class = User -%>
<div class="container">
  <div class="page-header">
  <h1>Friends</h1>
</div>
</div>


<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= form_for User.new , url: users_newfollow_path do |f| %>
  <p>
  <div class="form-group">
    <h4><%= f.label :'Your Friend E_mail' %></h4>
    <%= f.text_field :email, class: "form-control", placeholder: "enter e_mail" %>
  </div>
     <%= f.submit "Add", class: 'btn btn-primary' %>
</div>
</div>

  <!-- class :'btn btn-primary'  -->
</p>
<% end %><br/>

<div class="panel panel-default">
<div class="panel-heading">
  <div class="container">
    <h4>Friends List</h4>
  </div>
</div>
  <div class="panel-body">
  <br>
    <div class="row">
      <% @users.each do |user| %>
        <% unless user == current_user %>
        <% if current_user.following?(user) %>
          <div class="col-md-4">
            <div class="container">
             <img class='img-circle img-responsive'  width='50px' height='40px' src=""/>
              <h4><%= user.name %></h4>
              <span id="follow_user<%=user.id%>">
                <%= link_to(unfollow_user_path(user), :remote => true, :class => 'btn btn-danger') do %>
                  <i class="icon-remove icon-white"></i>
                  UnFriend
                <% end %><p></p>
            </div>
          </div>

        <%end %>
      <% end %>
    <% end %>
</div>
  </div>

</div>
</div>

yalla_notlob/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

yalla_notlob/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

yalla_notlob/app/views/users/unfollow.js.erb
$('#follow_user<%=@user.id%>').html('<%= escape_javascript(render :partial => "users/follow_user", :locals => {:user => @user}) %>');